#cloud-config
repo_update: true
repo_upgrade: all

packages:
  - nginx

runcmd:
  - cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
  - service nginx start
  - chkconfig nginx on
  - uname -n > /usr/share/nginx/html/index.html
  - mkdir /usr/share/nginx/html/target
  - cp /usr/share/nginx/html/index.html /usr/share/nginx/html/target/index.html
